org: brorlandi
app: qr-api
service: qr-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
      binaryMediaTypes:
          - '*/*'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
 - serverless-offline